services:
  - type: web
    name: Text Leech Bot
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/AshutoshGoswami24/text-leech-bot-for-render
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        value: "8551803950:AAEVdjf6EqoAlg21FEaxjQBJx0DrZsiyBak"
      - key: API_ID
        value: "31138834"
      - key: API_HASH
        value: "a6e6098b319618f10693005ee7a77d92"
      - key: WEBHOOK
        sync: false
      - key: PORT
        value: 8000  # Default port value, update if needed
